version: "3.9"
services:

  zookeeper:
    #container_name: zookeeper_container
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    #container_name: kafka_container
    image: debezium/kafka:1.1
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - ADVERTISED_LISTENERS=PLAINTEXT://host.docker.internal:9092
    links:
      - zookeeper
    ports:
      - 9092:9092

  kafdrop:
    #container_name: kafdrop_container
    image: obsidiandynamics/kafdrop:3.26.0
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    depends_on:
      - kafka
    ports:
      - 9000:9000
